spring.application.name=CGI_Praktika
spring.datasource.generate-unique-name=false
spring.datasource.name=tabledata
spring.datasource.url=jdbc:h2:file:./data/mydb
spring.h2.console.enabled=true
spring.sql.init.mode=always
