package com.example.cgi_praktika.repository;

import com.example.cgi_praktika.model.Reservation;
import com.example.cgi_praktika.model.Table;
import jakarta.annotation.PostConstruct;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Random;

@Repository
public class ReservationCollectionRepository {

    private final JdbcTemplate jdbcTemplate;

    public ReservationCollectionRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    private static Reservation mapRow(ResultSet rs, int rowNum) throws SQLException {
        return new Reservation(rs.getInt("reservationId"),
                rs.getInt("tableId"),
                rs.getTimestamp("reservationFrom").toLocalDateTime(),
                rs.getTimestamp("reservationUntil").toLocalDateTime()
        );
    }

    public List<Reservation> getAll() {
        String sql = "SELECT * FROM reservations";
        return jdbcTemplate.query(sql, ReservationCollectionRepository::mapRow);
    }

    public void createReservation(Reservation reservation) {
        String sql = "INSERT INTO reservations (tableId, reservationFrom, reservationUntil) VALUES (?, ?, ?)";
        jdbcTemplate.update(sql, reservation.tableId(), reservation.reservationFrom(), reservation.reservationUntil());
    }

    public void saveReservation(Reservation reservation) {
        String sql = "UPDATE reservations SET tableId=?, reservationFrom=?, reservationUntil=? WHERE reservationId=?";
        jdbcTemplate.update(sql, reservation.tableId(), reservation.reservationFrom(), reservation.reservationUntil());
    }

    public void deleteReservationById(int id) {
        String sql = "DELETE FROM reservations WHERE reservationId=?";
        jdbcTemplate.update(sql, id);
    }

    @SuppressWarnings("deprecation")
    public Optional<Reservation> getReservationById(int id) {
        String sql = "SELECT * FROM reservations WHERE reservationId=?";
        try {
            Reservation reservation = jdbcTemplate.queryForObject(sql, new Object[]{id}, ReservationCollectionRepository::mapRow);
            return Optional.ofNullable(reservation);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }


    @PostConstruct
    public void init() {
        // About half of this is generated by Copilot
        final List<Reservation> reservations = new ArrayList<>();
        final Random random = new Random();
        int nextReservationId = 10000;

        TableCollectionRepository repository = new TableCollectionRepository(jdbcTemplate);
        List<Table> tables = repository.getAll();

        // stop it from overpopulating when ran multiple times
        if (getAll().size() > 150) return;

        for (int dayOffset = 0; dayOffset < 14; dayOffset++) {
            for (Table table : tables) {

                // Try a few times to place a reservation without overlap
                for (int attempt = 0; attempt < 5; attempt++) {

                    // Random hour between 10 and 20 (so +2h doesn't exceed 22)
                    int startHour = 10 + random.nextInt(11); // 10–20 inclusive
                    LocalDateTime reservationFrom = LocalDateTime.now()
                            .plusDays(dayOffset)
                            .withHour(startHour)
                            .withMinute(0)
                            .withSecond(0)
                            .withNano(0);

                    LocalDateTime reservationUntil = reservationFrom.plusHours(2);

                    // overlap check
                    boolean conflict = reservations.stream().anyMatch(res -> {
                        if (!res.tableId().equals(table.tableId())) return false;
                        return reservationFrom.isBefore(res.reservationUntil()) &&
                                reservationUntil.isAfter(res.reservationFrom());
                    });

                    if (!conflict) {
                        Reservation reservation = new Reservation(
                                nextReservationId++,
                                table.tableId(),
                                reservationFrom,
                                reservationUntil
                        );
                        // add to db and to array to check for overlap
                        reservations.add(reservation);
                        createReservation(reservation);
                        break;
                    }
                }
            }
        }


    }
}
