### GET all tables
GET http://localhost:8080/api/tables

### POST new table
POST http://localhost:8080/api/tables
Content-Type: application/json

{
  "tableId": 2,
  "tableCapacity": 99,
  "tableZone": "private",
  "tablePreferences": "window",
  "startingPosX": 1,
  "startingPosY": 2,
  "tableWidth": 55
}

### PUT new table
PUT http://localhost:8080/api/tables/2
Content-Type: application/json

{
  "tableId": 2,
  "tableCapacity": 101,
  "tableZone": "private",
  "tablePreferences": "window",
  "startingPosX": 55,
  "startingPosY": 2,
  "tableWidth": 55
}

### DELETE table by ID
DELETE http://localhost:8080/api/tables/2



### GET all reservations
GET http://localhost:8080/api/reservations

### POST new reservations
POST http://localhost:8080/api/reservations
Content-Type: application/json

{
  "tableId": 2,
  "tableCapacity": 99,
  "tableZone": "private",
  "tablePreferences": "window",
  "startingPosX": 1,
  "startingPosY": 2,
  "tableWidth": 55
}

### PUT new reservation
PUT http://localhost:8080/api/reservations/2
Content-Type: application/json

{
  "tableId": 2,
  "tableCapacity": 101,
  "tableZone": "private",
  "tablePreferences": "window",
  "startingPosX": 55,
  "startingPosY": 2,
  "tableWidth": 55
}

### DELETE reservation by ID
DELETE http://localhost:8080/api/reservations/2